# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Review.create(review_date: '2016-09-06', name: 'Broadway Pizza', address: '2709 Broadway, New York, NY', score: 6.4, url: 'http://www.barstoolsports.com/boston/one-bite-with-davey-pageviews-broadway-pizza/')
Review.create(review_date: '2016-09-07', name: '2 Bros Pizza', address: '755 6th Ave, New York, NY', score: 5.9, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-2-bros-pizza/')
Review.create(review_date: '2016-09-08', name: 'Empire Pizza', address: '314 5th Ave, New York, NY', score: 7.2, url: 'http://www.barstoolsports.com/boston/pizza-review-empire-pizza/')
Review.create(review_date: '2016-09-12', name: "Waldy's", address: '800 6th Ave, New York, NY', score: 7.8, url: 'http://www.barstoolsports.com/boston/pizza-review-waldys/')
Review.create(review_date: '2016-09-13', name: 'Bella Napoli', address: '257 7th Ave, New York, NY', score: 8.5, url: 'http://www.barstoolsports.com/boston/one-bite-with-davey-pageviews-bella-napoli-with-special-guest-sensational-the-rapper/')
Review.create(review_date: '2016-09-14', name: 'Little Italy Pizza', address: '2 E 33rd St, New York, NY', score: 6.4, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review/')
Review.create(review_date: '2016-09-15', name: 'Pizza 23', address: '268 W 23rd St, New York, NY', score: 5.9, url: 'http://www.barstoolsports.com/boston/el-pres-pizza-review-pizza-23-bonus-pizza-review-at-great-burrito-wait-what/')
Review.create(review_date: '2016-09-15', name: 'Great Burrito', address: '100 W 23rd St, New York, NY', score: 0, url: 'http://www.barstoolsports.com/boston/el-pres-pizza-review-pizza-23-bonus-pizza-review-at-great-burrito-wait-what/')
Review.create(review_date: '2016-09-16', name: 'Cafe Rustico II', address: '25 W 35th St, New York, NY', score: 8.1, url: 'http://www.barstoolsports.com/boston/el-pres-pizza-review-pizza-23-bonus-pizza-review-at-great-burrito-wait-what/')
Review.create(review_date: '2016-09-20', name: 'Tappo Thin Crust', address: '49 W 24th St, New York, NY ', score: 7.3, url: 'http://www.barstoolsports.com/boston/pizza-review-tappo-thin-crust/')
Review.create(review_date: '2016-09-20', name: 'NY Pizza Suprema (Regular Slice)', address: '413 8th Ave, New York, NY', score: 8.2, url: 'http://www.barstoolsports.com/boston/live-pizza-review-ny-pizza-suprema/')
Review.create(review_date: '2016-09-20', name: 'NY Pizza Suprema (Sicilian Slice)', address: '413 8th Ave, New York, NY', score: 5.1, url: 'http://www.barstoolsports.com/boston/live-pizza-review-ny-pizza-suprema/')
Review.create(review_date: '2016-09-26', name: 'Don Pepi', address: 'One Penn Plaza, 2 Pennsylvania Plaza, New York, NY', score: 3.9, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-don-pepi/')
Review.create(review_date: '2016-09-28', name: "Roberta's (at Madison Square Eats)", address: 'General William Jenkins Worth Monument, 5th Ave, New York, NY', score: 8.0, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-robertas/')
Review.create(review_date: '2016-10-03', name: "Rossopomodoro", address: '118 Greenwich Ave, New York, NY', score: 8.0, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-rossopomodoro/')
Review.create(review_date: '2016-10-05', name: "PN Wood Fired Pizza", address: '2 W 28th St, New York, NY', score: 6.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-pn-wood-fired-pizza/')
Review.create(review_date: '2016-10-10', name: "Catfish Bifs", address: '75 W 11th Ave, Columbus, OH', score: 1.4 , url: 'http://www.barstoolsports.com/boston/barstool-pizza-reviews-from-ohio-catfish-bifs-and-dantes-inferno/')
Review.create(review_date: '2016-10-10', name: "Dante's Inferno (Progressive Field)", address: '2401 Ontario St, Cleveland, OH', score: 0, url: 'http://www.barstoolsports.com/boston/barstool-pizza-reviews-from-ohio-catfish-bifs-and-dantes-inferno/')
Review.create(review_date: '2016-10-11', name: "Frank's Express Pizza", address: '127 E 23rd St, New York, NY', score: 3.8 , url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-franks/')
Review.create(review_date: '2016-10-12', name: "Pizza Paradise", address: '12 W 18th St, New York, NY', score: 7.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-pizza-paradise-bonus-persian-food-review/')
Review.create(review_date: '2016-10-14', name: "Lazzara's Pizza Cafe", address: '221 W 38th St #2, New York, NY', score: 9.3, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-lazzaras-pizza/')
Review.create(review_date: '2016-10-18', name: "Vezzo Thin Crust Pizza", address: '178 Lexington Ave, New York, NY', score: 9.0, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-vezzo/')
Review.create(review_date: '2016-10-19', name: "Famous Fimiglia", address: '488 8th Ave, New York, NY', score: 7.4 , url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-famous-fimiglia-featuring-my-dad/')
Review.create(review_date: '2016-10-20', name: "DJ Pizza", address: '120 E 34th St, New York, NY', score: 6.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-dj-pizza/')
Review.create(review_date: '2016-10-21', name: "Bravo Pizza", address: '1367 Broadway, New York, NY', score: 8.3 , url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-2/')
Review.create(review_date: '2016-10-24', name: "OTTO Enoteca e Pizzeria", address: '1 5th Ave, New York, NY', score: 5.4, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-otto-and-enoteca-and-rosas-pizza/')
Review.create(review_date: '2016-10-24', name: "Rosa's Pizza", address: '2 W 14th St, New York, NY', score: 4.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-otto-and-enoteca-and-rosas-pizza/')
Review.create(review_date: '2016-10-25', name: "Pastafina", address: '388 3rd Ave, New York, NY', score: 7.9, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-pastafina/')
Review.create(review_date: '2016-10-26', name: "Doughboys", address: '451 3rd Ave, New York, NY', score: 4.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-doughboys/')
Review.create(review_date: '2016-10-27', name: "Pick and Pay Gyro and Pizza", address: '30 Lexington Ave, New York, NY', score: 2.4, url: 'http://www.barstoolsports.com/boston/barstool-sports-pizza-review-pick-and-pay/')
Review.create(review_date: '2016-10-28', name: "J's Pizza", address: '98 7th Ave, New York, NY', score: 6.8, url: 'http://www.barstoolsports.com/boston/barstool-pizza-review-js-pizza/')
